### PR TITLE
Revamp to primarily c++

### PR DESCRIPTION
**Pull request by kkauder**
### Briefly, what does this PR introduce?
Revamp to primarily c++ 

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### CODE REVIEW

**Comment by kkauder** [comment]
@simonge @bsterwerf 
This PR would make my C++ version the default and move the python parts into a subdirectory. Would this work for you?
One of the reasons is that I want to make an official merged file and want to adhere to the policy of corresponding tagged repos with code and steering info.

**Review by simonge — APPROVED** [review]
The only immediate changes I would have suggested are in my PR to this branch fixing the command line arguments. The other branch I've produces takes the C++ness a bit further and adds some timing structure. I'm not sure if we should introduce CI checks before or after merging that.

**Comment by kkauder** [comment]
@bsterwerf Speak now or forever hold your peace :)

**Review by bsterwerf — APPROVED** [review]
Looks great to me!

**Comment by kkauder** [comment]
@simonge Go ahead and make a PR for those! I did fix some argument issues, but I may well have overlookd more.

**Pull request merged**
